<a href="https://colab.research.google.com/github/aaravpathak9984-boop/Python_class_lec/blob/main/Ds_Lec6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:


dct = {
    'name': ["Aarav", "devo", "kiran", "mani", "sagar", "viaks"],
    'age': [10, 20, 30, 40, 50, 60],
    'roll': [1, 2, 3, 4, 5, 6]
}

# Fix: Define the index here
df = pd.DataFrame(dct, index=['a', 'b', 'x', 'd', 'e', 'f'])

display(df) # to print df

    name  age  roll
a  Aarav   10     1
b   devo   20     2
x  kiran   30     3
d   mani   40     4
e  sagar   50     5
f  viaks   60     6

# Pandas Data Exploration & Filtering Cheat Sheet

This notebook serves as a reference guide for data exploration, structural analysis, indexing, and conditional filtering using Pandas.

---

## 1. Loading & Viewing Data

### Load Dataset
```python
import pandas as pd

df = pd.read_csv("student_data.csv")
```

### Inspecting Rows
* **`df.head(n)`**: Views the first `n` rows of the dataset.
* **`df.tail(n)`**: Views the last `n` rows of the dataset.

```python
df.head(3)  # Displays the first 3 rows
df.tail(4)  # Displays the last 4 rows
```

---

## 2. Metadata & Structure

### Structural Attributes
* **`df.shape`**: Returns a tuple representing the dataset dimensions `(rows, columns)`.
* **`df.columns`**: Lists all column labels.
* **`df.index`**: Provides the row index range details.

```python
df.shape    # Gives the value of rows, cols
df.columns  # Checks the column names
df.index    # Gives the RangeIndex (e.g., start, stop, step)
```

### Metadata Summary
* **`df.info()`**: Prints critical metadata including file type, row/column counts, data types (`dtype`), and memory usage.

```python
df.info()   # Gives data of data (metadata)
```

---

## 3. Statistical Analysis

### Descriptive Statistics
* **`df.describe()`**: Summarizes the central tendency, dispersion, and shape of the numerical distribution.

### Understanding Percentiles (Quartiles)
* **`50%` (Median / Q2)**: The absolute middle value of the data (from 1 to 100).
* **`25%` (Q1)**: The median of the lower half of the data (from 1 to 50).
* **`75%` (Q3)**: The median of the upper half of the data (from 50 to 100).

```python
df.describe()  # Computes Q1, Q2, Q3, mean, std, min, and max
```

---

## 4. Selecting & Subsetting Columns

### Single Column Selection
* Returns a single dimension Pandas `Series`.
```python
df['internet_usage']
```

### Multiple Column Selection
* Pass a list of column names inside a second set of brackets to return a subset `DataFrame`.
```python
df[['internet_usage', 'study_hours']]
```

---

## 5. Indexing & Filtering (`iloc` vs `loc`)

### Pure Integer-Location Based Indexing (`iloc`)
* Standard syntax: `df.iloc[row_position, column_position]`
* Strictly works on integer position index values, completely ignoring label names.

```python
df.iloc[0]  # Extracts the absolute first row of the DataFrame
```

### Label-Based Indexing & Filtering (`loc`)
* Standard syntax: `df.loc[row_label/condition, column_label]`
* Works on column names, row labels, and conditional boolean masks.

```python
# Filters rows where study_hours equals 11, selects specific columns, and slices positions 1 to 7
df.loc[df['study_hours'] == 11, ['study_hours', 'sleep_hours']].iloc[1:8]

# Filters rows where study_hours equals 8 and extracts specific columns into a new DataFrame
df1 = df.loc[df['study_hours'] == 8][['study_hours', 'sleep_hours']]
```

---

## 6. Essential Add-on Functions for Reference

### Data Cleaning & Integrity
* **`df.isnull().sum()`**: Counts missing or `NaN` values across every column.
* **`df.duplicated().sum()`**: Checks for completely identical duplicate rows.

```python
df.isnull().sum()  # Essential before applying filters
df.duplicated().sum()
```

### Sorting Data
* **`df.sort_values()`**: Sorts your dataset by specific column values.

```python
# Sorts rows by study hours from highest to lowest
df.sort_values(by='study_hours', ascending=False)
```

### Categorical Aggregation
* **`df['column'].value_counts()`**: Counts unique occurrences in a categorical column.

```python
df['internet_usage'].value_counts()  # Tells you how many times each value appears
```

In [115]:
df=pd.read_csv("student_data.csv")
df.head(3) # first 3 rows
df.tail(4) # last 4 rows

df.shape    #  gives the value of rows ,col;

#/ df.info()   # gives data of data(metadata) (like files ki info here its csv type also row,col etc,dtype)

df.describe() # gives about q1,q2,q3 _> 1 to 100 median q2 , 1 to 50 median q1, 50 t0 100 median q3


df.columns  # to check about the columns data like name , and dtype:::

df.index    # gives range index;


df[['internet_usage','study_hours']]

df.iloc[0]


df.loc[df['study_hours']==11,['study_hours','sleep_hours']] # to filter data where study hours ==11

df['age']=20
df['null']=None

In [107]:
df[['study_hours','internet_usage']]

# to excess the row of the data , this gives row in column format
df.iloc[0:5]

# to filter the data according to study_hours
df.loc[df['study_hours']==11]
# to filter the data according to study_hours , but it gives only two columns study_hours and sleep_hours
df.loc[df['study_hours']==11,['study_hours','sleep_hours']]

df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4:8]

#
df2= df.loc[df['study_hours']==11]
df2[['study_hours','sleep_hours']]

df.loc[df['assignments_completed']==8].iloc[1]

# loc and iloc works on rows but to excess column we use this syntax
df[df['assignments_completed']>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [113]:
df=pd.read_csv("student_data.csv")


df.rename(columns={'assignments_completed':'ass_done'},inplace=True)  # returns another data frame with name changed if done inplace=True then it means its done with in the plce;
display(df)

,study_hours,attendance,sleep_hours,internet_usage,ass_done,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [118]:
# remove rows or columns

# df = df.drop(columns=['ass_done'])
# Or using the axis parameter:
# df = df.drop(['ass_done'], axis=1)
display(df)




# remove missing values

dfn = df.dropna(axis= 1)
display(dfn)


#sort values by colums:

df.sort_values(by='study_hours')


# Sort index from lowest to highest (0, 1, 2...)
df_restored = df.sort_index(ascending=False)
display(df_restored.head())

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age,null
0,7,56,8,7,10,62,100.00,Placed,20,None
1,4,69,5,3,8,56,100.00,Placed,20,None
2,11,60,7,6,10,45,100.00,Placed,20,None
3,8,99,9,8,4,55,90.17,Placed,20,None
4,5,52,8,6,8,40,78.82,Placed,20,None
...,...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20,None
9996,7,98,6,9,4,87,100.00,Placed,20,None
9997,10,44,8,5,10,37,95.94,Placed,20,None
9998,10,75,7,5,8,52,88.61,Placed,20,None
9999,2,70,6,11,16,52,78.96,Placed,20,None

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age,null
9999,2,70,6,11,16,52,78.96,Placed,20,None
9998,10,75,7,5,8,52,88.61,Placed,20,None
9997,10,44,8,5,10,37,95.94,Placed,20,None
9996,7,98,6,9,4,87,100.00,Placed,20,None
9995,2,58,9,7,8,88,69.31,Not Placed,20,None

In [123]:
 # check for missing vlauess
df.isnull()

## check fro non-missing vlauess

df.notnull()

##replace missing values

df.fillna(0)

# find unique values

df.unique() # for a series only

/tmp/ipykernel_681/4063209160.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(0)

AttributeError: 'DataFrame' object has no attribute 'unique'

# Pandas Advanced Data Cleaning & Filtering Cheat Sheet

This notebook serves as a quick-reference guide for detecting and handling missing values, deleting dimensions, sorting, slicing, and advanced structural filtering.

---

## 1. Handling Missing & Null Values

### Detection
* **`df.isnull()`**: Returns a boolean mask of the same shape, where `True` indicates missing/NaN values.
* **`df.notnull()`**: Returns a boolean mask where `True` indicates valid, non-missing values.

```python
df.isnull()   # Check for missing values
df.notnull()  # Check for non-missing values
```

### Remediation & Cleaning
* **`df.fillna(value)`**: Replaces missing values with a specified placeholder value (e.g., 0).
* **`df.dropna(axis=1)`**: Drops entire columns if they contain any missing values. Set `axis=0` to drop rows instead.

```python
df.fillna(0)            # Replace missing values with 0
dfn = df.dropna(axis=1) # Remove columns with missing values
display(dfn)
```

---

## 2. Dropping & Identifying Elements

### Deleting Dimensions
* **`df.drop()`**: Removes specific labels or names from rows (`axis=0`) or columns (`axis=1`).

```python
# Remove specific columns using the columns argument
df = df.drop(columns=['ass_done'])

# Alternatively, achieve the same result using the axis parameter (axis=1 means columns)
# df = df.drop(['ass_done'], axis=1)
display(df)
```

### Finding Unique Values
* **`df['column'].unique()`**: Returns an array of all unique elements in a specific column.
* **`df['column'].nunique()`**: Returns the count of unique elements.

```python
df['study_hours'].unique()   # Find unique values in a column
df['study_hours'].nunique()  # Count unique values in a column
```

---

## 3. Sorting Operations

### Sorting Data Values
* **`df.sort_values(by='column_name')`**: Sorts rows by the values of a specified column. Default is ascending order.

```python
df.sort_values(by='study_hours')  # Sort values by study_hours column
```

### Sorting Data Index
* **`df.sort_index()`**: Reorganizes the DataFrame rows by their original sequence numbers or labels.

```python
# Sort index from highest to lowest (e.g., ...2, 1, 0)
df_restored = df.sort_index(ascending=False)
display(df_restored.head())
```

---

## 4. Indexing, Slicing & Structural Extraction

### Row Slicing with `iloc`
* **`df.iloc[start:stop]`**: Extracts exact row positions. When given an integer range, it displays multiple rows horizontally (or structural row context in a table format).

```python
df.iloc[0:5]  # Access rows 0 to 4 of the data (gives rows in structural format)
```

### Column Subsetting
* Pass a list of strings directly into brackets to view a narrow subset of columns.

```python
df[['study_hours', 'internet_usage']]
```

---

## 5. Advanced Conditional Filtering (`loc` vs Boolean Masking)

### Conditional Filtering with `loc`
`df.loc[row_condition, column_selection]` filters rows safely and lets you pick target fields or chain positional adjustments afterwards.

```python
# 1. Filter rows completely based on a condition
df.loc[df['study_hours'] == 11]

# 2. Filter rows according to study_hours, but return only specific columns
df.loc[df['study_hours'] == 11, ['study_hours', 'sleep_hours']]

# 3. Filter rows, pick target columns, and then slice positional index rows 4 to 7
df.loc[df['study_hours'] == 11, ['study_hours', 'sleep_hours']].iloc[4:8]

# 4. Alternative multi-step approach: filter rows first, save variable, then view target columns
df2 = df.loc[df['study_hours'] == 11]
df2[['study_hours', 'sleep_hours']]

# 5. Filter by a different attribute and access the second resulting row (index 1) directly
df.loc[df['assignments_completed'] == 8].iloc[1]
```

### Direct Boolean Masking (Row-Level Filtering via Column Logic)
* While `loc` and `iloc` are robust row/column engines, direct boolean syntax provides a rapid, convenient format to extract rows meeting column thresholds.

```python
# Direct column lookup inside brackets to return matched rows
df[df['assignments_completed'] > 3]
```

---

## 6. Essential Add-on Functions for Advanced Analysis

### Multi-Conditional Filtering
* Combine parameters using bitwise operators: `&` (AND), `|` (OR). Wrap each condition inside parentheses.

```python
# Filter rows where both conditions match simultaneously
df[(df['study_hours'] > 8) & (df['internet_usage'] == 'Low')]
```

### Element Grouping & Aggregation
* **`df.groupby('column').mean()`**: Groups rows sharing common categories and computes summaries for numerical columns.

```python
# Calculate average sleep and study habits based on assignment levels
df.groupby('assignments_completed')[['study_hours', 'sleep_hours']].mean()
```